### ISSUE TITLE
Generics Error

### ISSUE THREAD

**Issue by Arpit1496** [den0206/riverpod_builder#18]
The code builder  leaves "Generics" in 2 functions:

1).  _copyWith: The create Function parameter does not consider Generics and generates a compile time error.

`ListBlocProvider _copyWith(
    ListBloc Function() create,
  )`

2). == override: The first condition of ==  does not consider generics and hence 2 objects are never equal and generate a compile time error.

`  @override
  bool operator ==(Object other) {
    return other is ListBlocProvider &&
        other.runtimeType == runtimeType &&
        other.getData == getData;
  }`

 A sample error message is added for better understanding.

![image](https://github.com/den0206/riverpod_builder/assets/47178423/cf40d946-d8de-4daf-8b45-cc6f7e03dbfc)

**Comment by den0206** [comment]
@Arpit1496 
Hi Thanks for using this package. 
I've updated `0.2.1`, check it out.

**Comment by Arpit1496** [comment]
Oh great. Thanks a lot. That was quick.
I will check it out and update you. Meanwhile closing the issue.
